config/routes.rb
Rails.application.routes.draw do
root to: "home#index"

  devise_for :users
  resources :parties

end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
    params.require(:party).permit(:name, :date, :max_attendees, :age_range, :description, :what_to_bring, :rules)
      .merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/home/index.html.erb
<div class= "text-center">
  <h1>We are <strong>PARTY CRASHERZ.</strong></h1>
  <h3>Find a party. Crash a party.</h3>
  <small>Are you tired of living a boring life? It's time to get out more!</small>

  <div id="sign_up_buttons">
    <% if current_user.present? %>
    <%= link_to("Sign Out", destroy_user_session_url, method: :delete, class: "btn btn-large btn-danger") %>
    <%= link_to("Throw a PARTY!", new_party_url, class: "btn btn-large btn-success") %>
    <%= link_to("Find a PARTY!", parties_url, class: "btn btn-large btn-success") %>
    <% else %>
    <%= link_to("Sign Up", new_user_registration_url, class: "btn btn-large btn-info") %>
    <%= link_to("Sign In", new_user_session_url, class: "btn btn-large btn-rebeccapurple") %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartyCrasherz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="homepage">

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :max_attendees %><br>
    <%= f.number_field :max_attendees %>
  </div>
  <div class="field">
    <%= f.label :age_range %><br>
    <%= f.text_field :age_range %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :what_to_bring %><br>
    <%= f.text_area :what_to_bring %>
  </div>
  <div class="field">
    <%= f.label :rules %><br>
    <%= f.text_area :rules %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parties</h1>

<table class="text-center">
  <thead> 
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Date</th>
      <th class="text-center">Max attendees</th>
      <th class="text-center">Age range</th>
      <th class="text-center">Description</th>
      <th class="text-center">What to bring</th>
      <th class="text-center">Rules</th>
      <th class="text-center">Host</th>
      <th class="text-center" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= party.date %></td>
        <td><%= party.max_attendees %></td>
        <td><%= party.age_range %></td>
        <td><%= party.description %></td>
        <td><%= party.what_to_bring %></td>
        <td><%= party.rules %></td>
        <td><%= party.user.try(:email) %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @party.date %>
</p>

<p>
  <strong>Max attendees:</strong>
  <%= @party.max_attendees %>
</p>

<p>
  <strong>Age range:</strong>
  <%= @party.age_range %>
</p>

<p>
  <strong>Description:</strong>
  <%= @party.description %>
</p>

<p>
  <strong>What to bring:</strong>
  <%= @party.what_to_bring %>
</p>

<p>
  <strong>Rules:</strong>
  <%= @party.rules %>
</p>

<p>
  <strong>Host:</strong>
  <%= @party.user.try(:email) %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>